host: "localhost"
#host: "https://space-tycoon.garage-trip.cz"
#host: "?"
<<<<<<< Updated upstream
user: "ducks"
password: "ducklings"

# dev 
# host: "46.101.112.32"
# #host: "?"
# user: "ducks"
# password: "123"
=======
user: "test"
password: "test"
logging_config: "log/logging.ini"
>>>>>>> Stashed changes
