#host: "localhost"
host: "https://space-tycoon.garage-trip.cz"
#host: "?"
user: "ducks"
password: "ducklings"
logging_config: "log/logging.ini"

# dev 
# host: "46.101.112.32"
# #host: "?"
# user: "ducks"
# password: "123"