#host: "localhost"
host: "https://space-tycoon.garage-trip.cz"
user: "ducks"
password: "ducklings"
logging_config: "log/logging.ini"


# production
# host: "https://space-tycoon.garage-trip.cz"
# user: "ducks"
# password: "ducklings"

# dev 
# host: "46.101.112.32"
# user: "ducks"
# password: "ducklings"